# specify the 3-token values.    
USER: alex_1290424120_biz_api1.gmail.com
PWD:  8BWX5UNLVW8NHJJD
SIGNATURE: AVmnfSdY0Wvx0KaIEj4kJP0Gc4QRAmrGtgS9hvuhjXXFjIbnauqdZl8l
       
   
#    @@endpoints 
SERVER:  api-3t.sandbox.paypal.com
SERVICE: /nvp/
# Proxy information of the client environment.   @@proxy_info 
USE_PROXY:  false
ADDRESS: nil
PORT: nil
USER: nil
PASSWORD: nil 


# Information needed for tracking purposes.   @@client_info   
VERSION: 3.0
SOURCE: PayPalRubySDKV1.2.0
