# specify the 3-token values.
#USER: akshay_api1.keupons.com
#PWD:  VYE9TNTSKZ5W7WFC
#SIGNATURE: AKhpjCvdj3KVB2-fNZqxoZKi4iWFAlC-DupHgtdY2t3LB7uSb20IjddJ

USER: alex_1290492158_biz_api1.gmail.com
PWD:  1290492213
SIGNATURE: A8enwJLBFTWWh63BEP0tfysIp7.SAt6cVx19.lNEM3Y47INGmrLlh9a6
       
   
#    @@endpoints 
SERVER:  api-3t.paypal.com
SERVICE: /nvp/
# Proxy information of the client environment.   @@proxy_info 
USE_PROXY:  false
ADDRESS: nil
PORT: nil
USER: nil
PASSWORD: nil 


# Information needed for tracking purposes.   @@client_info   
VERSION: 3.0
SOURCE: PayPalRubySDKV1.2.0
